import type { Metadata } from 'next';

import localFont from 'next/font/local';

import Sidebar from '@/components/Sidebar/Sidebar';
import cn from '@/utils/cn';

import './globals.css';

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(`${pretendard.variable} antialiased`, 'relative h-dvh')}>
        <Sidebar />
        <div className="absolute left-[192px] top-0 h-full w-[calc(100dvw-192px)] p-4">
          {children}
        </div>
      </body>
    </html>
  );
}
